server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    consul:
      port: 8500
      host: consul
      discovery: instanceId=${spring.application.name}:${random.int}

zuul:
  prefix: /api
  ? sensitive-headers
  routes:
    todo-service:
      path: /todo**
      serviceId: todo-service
      strip-prefix: false
    user-service:
      path: /user**
      serviceId: user-service
      strip-prefix: false
